services:
  - type: web
    name: gestion-ventas
    env: dotnet
    plan: free
    runtime: dotnet
    buildCommand: "dotnet build"
    startCommand: "dotnet GestionVentas.dll
    envVars:
      - key: CONNECTION_STRING
        value: "AQUÍ_LUEGO_PONES_LA_CADENA_DE_CONEXIÓN_DE_RENDER"
