services:
  - type: web
    name: gestion-ventas
    env: dotnet
    plan: free
    buildCommand: "dotnet publish -c Release"
    startCommand: "dotnet bin/Release/net8.0/TuProyecto.dll"
    envVars:
      - key: CONNECTION_STRING
        value: "AQUÍ_LUEGO_PONES_LA_CADENA_DE_CONEXIÓN_DE_RENDER"
